name: Publish .NET App
on:
  workflow_call:
  push:
  pull_request:
  merge_group:

jobs:
  publish:
    name: Publish for all platforms
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rid: [
          win-x64,
          win-arm64,
          linux-x64,
          linux-arm64,
          osx-x64,
          osx-arm64,
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish for ${{ matrix.rid }}
        run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -o ./publish/${{ matrix.rid }}

      - name: Upload artifacts for ${{ matrix.rid }}
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.rid }}
          path: ./publish/${{ matrix.rid }}