name: Publish .NET App
on:
  workflow_call:
  push:
  pull_request:
  merge_group:

env:
  PROJECT_NAME: JsonhCli
  DOTNET_VERSION: 10.x

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        framework: [net10.0]
        target:
          [
            { rid: win-x64, os: windows-latest },
            { rid: win-arm64, os: windows-latest },
            { rid: linux-x64, os: ubuntu-24.04 },
            { rid: linux-arm64, os: ubuntu-24.04-arm },
            { rid: osx-x64, os: macos-latest },
            { rid: osx-arm64, os: macos-latest },
          ]

    runs-on: ${{ matrix.target.os }}
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v6

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Download dependencies
      - name: Download dependencies
        run: dotnet restore

      # Build app
      - name: Build app
        run: >-
          dotnet publish ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj
          -c Release
          -r ${{ matrix.target.rid }}
          --self-contained true
          -o ./publish/${{ env.PROJECT_NAME }}-${{ matrix.target.rid }}/${{ env.PROJECT_NAME }}-${{ matrix.target.rid }}
          -p:PublishSingleFile=true
          -p:PublishAot=true
          -p:PublishTrimmed=true
          -p:GeneratePackageOnBuild=false
          -f ${{ matrix.framework }}

      # Upload the build
      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.target.rid }}
          path: ./publish/${{ env.PROJECT_NAME }}-${{ matrix.target.rid }}