name: Publish .NET App
on:
  workflow_call:
  push:
  pull_request:
  merge_group:

env:
  DOTNET_VERSION: 9.x

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            { rid: win-x64, os: windows-latest },
            { rid: win-arm64, os: windows-latest },
            { rid: linux-x64, os: ubuntu-24.04 },
            { rid: linux-arm64, os: ubuntu-24.04-arm },
            { rid: osx-x64, os: macos-latest },
            { rid: osx-arm64, os: macos-latest },
          ]
    
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet restore
      - run: dotnet publish -c Release -r ${{ matrix.target.rid }} --self-contained true -o ./publish/${{ matrix.target.rid }}
      - uses: actions/upload-artifact@v4
        with:
          name: JsonhCli-${{ matrix.target.rid }}
          path: ./publish/${{ matrix.target.rid }}

  merge:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: JsonhCli
          pattern: JsonhCli-*
          delete-merged: true
